version: '3.7'
services:
    nginx:
        image: nginx
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf
        depends_on:
            - httpbin
        ports:
            - 80:80
    httpbin:
        image: kennethreitz/httpbin
        expose:
            - 80
